version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: musicapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: musicapp
      POSTGRES_USER: musicapp_user
      POSTGRES_PASSWORD: musicapp_password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/backups:/backups
    networks:
      - musicapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicapp_user -d musicapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: musicapp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@musicapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - musicapp_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  musicapp_network:
    driver: bridge
